-- 1. Enable UUID extension
create extension if not exists "uuid-ossp";

-- 2. Clients
create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  name text not null,
  email text not null,
  phone text not null,
  instagram_handle text,
  wedding_date date,
  venue text,
  guest_count integer,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  deleted_at timestamptz
);

-- 3. Bookings
create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete cascade,
  service_package text not null,
  event_date date not null,
  venue text not null,
  guest_count integer,
  status text check (status in ('inquiry', 'negotiation', 'approved', 'hold_expired', 'down_payment', 'paid', 'confirmed', 'cancelled')) default 'inquiry',
  total_amount numeric default 0,
  dp_amount numeric default 0,
  hold_expires_at timestamptz,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 4. Quotations
create table if not exists public.quotations (
  id bigint generated by default as identity primary key,
  booking_id bigint references public.bookings(id) on delete cascade,
  quote_number text not null,
  base_items jsonb not null default '[]'::jsonb,
  selected_addons jsonb default '[]'::jsonb,
  subtotal numeric not null,
  discount numeric default 0,
  grand_total numeric not null,
  dp_required numeric not null,
  valid_until timestamptz,
  status text check (status in ('draft', 'sent', 'accepted', 'expired')) default 'draft',
  pdf_path text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 5. Contracts
create table if not exists public.contracts (
  id bigint generated by default as identity primary key,
  booking_id bigint references public.bookings(id) on delete cascade,
  quotation_id bigint references public.quotations(id) on delete cascade,
  spk_number text not null,
  terms_content text not null,
  client_signature_data text,
  client_signature_path text,
  signed_ip text,
  signed_at timestamptz,
  pdf_path text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 6. Payments
create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  booking_id bigint references public.bookings(id) on delete cascade,
  deal_id bigint references public.deal_customers(id) on delete set null,
  payment_method text,
  transaction_id text not null,
  amount numeric not null,
  fee numeric default 0,
  status text default 'pending',
  paid_at timestamptz,
  payment_channel text,
  external_id text,
  qr_code_url text,
  va_number text,
  bank text,
  raw_webhook jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 7. Schedules
create table if not exists public.schedules (
  id bigint generated by default as identity primary key,
  booking_id bigint references public.bookings(id) on delete cascade,
  title text,
  description text,
  location text,
  source text default 'booking',
  start_datetime timestamptz not null,
  end_datetime timestamptz not null,
  google_event_id text,
  google_event_link text,
  synced_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 7b. Google Calendar Integration Settings & Tokens
create table if not exists public.google_calendar_settings (
  id integer primary key default 1,
  client_id text,
  client_secret text,
  access_token text,
  refresh_token text,
  token_expiry timestamptz,
  google_email text,
  calendar_id text default 'primary',
  is_connected boolean default false,
  auto_sync boolean default true,
  last_synced_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 8. Inquiries
create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  whatsapp text not null,
  email text,
  event_date date,
  venue text,
  package text,
  guest_count integer,
  message text,
  source text,
  consent boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 9. AI Leads
create table if not exists public.ai_leads (
  id bigint generated by default as identity primary key,
  session_id text not null,
  name text,
  phone text,
  email text,
  interest text,
  messages integer default 0,
  source text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 10. Portfolio Items
create table if not exists public.portfolio_items (
  id bigint generated by default as identity primary key,
  title text not null,
  undertone text,
  venue text,
  image_path text,
  is_highlighted boolean default false,
  sort_order integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 11. Gated Tokens
create table if not exists public.gated_tokens (
  id bigint generated by default as identity primary key,
  booking_id bigint references public.bookings(id) on delete cascade,
  token text not null,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 12. Enable RLS
alter table public.clients enable row level security;
alter table public.bookings enable row level security;
alter table public.quotations enable row level security;
alter table public.contracts enable row level security;
alter table public.payments enable row level security;
alter table public.schedules enable row level security;
alter table public.inquiries enable row level security;
alter table public.ai_leads enable row level security;
alter table public.portfolio_items enable row level security;
alter table public.gated_tokens enable row level security;
